
public enum PoseLandmarkName
{
    Nose = 0,
    LeftEyeInner = 4,
    LeftEye = 5,
    LeftEyeOuter = 6,
    RightEyeInner = 1,
    RightEye = 2,
    RightEyeOuter = 3,
    LeftEar = 8,
    RightEar = 7,
    MouthLeft = 10,
    MouthRight = 9,
    LeftShoulder = 12,
    RightShoulder = 11,
    LeftElbow = 14,
    RightElbow = 13,
    LeftWrist = 16,
    RightWrist = 15,
    LeftPinky = 18,
    RightPinky = 17,
    LeftIndex = 20,
    RightIndex = 19,
    LeftThumb = 22,
    RightThumb = 21,
    LeftHip = 24,
    RightHip = 23,
    LeftKnee = 26,
    RightKnee = 25,
    LeftAnkle = 28,
    RightAnkle = 27,
    LeftHeel = 30,
    RightHeel = 29,
    LeftFootIndex = 32,
    RightFootIndex = 31
}